- name: "Add Node from Nodesource"
  become: true
  shell:  |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
- name: "Install js"
  become: true
  apt:
     name: ["nodejs"]
     state: latest
     update_cache: yes
     
- name: "install PM2 Globally"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "update packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes  
